# Generated by Django 5.2.4 on 2025-07-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('business', 'Business'), ('legal', 'Legal'), ('agriculture', 'Agriculture'), ('technology', 'Technology'), ('design', 'Design'), ('marketing', 'Marketing'), ('real_estate', 'Real Estate'), ('engineering', 'Engineering'), ('education', 'Education'), ('health', 'Health'), ('travel_hospitality', 'Travel Hospitality')], default='business', max_length=20, unique=True),
        ),
    ]
